import { Inter } from 'next/font/google';
import Link from 'next/link';
import { FaArrowLeft, FaArrowRight, FaShoppingCart } from 'react-icons/fa';
import styles from './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <div>
              <Link
                href="/"
                style={{
                  color: 'black',
                  textDecoration: 'none',
                  fontSize: '1.5rem',
                }}
              >
                Cofeez
              </Link>
            </div>
            <ul>
              <li>
                <Link
                  href="/"
                  style={{
                    color: 'black',
                    textDecoration: 'none',
                  }}
                >
                  Home
                </Link>
              </li>
              <li>
                <Link
                  href="/products"
                  style={{
                    color: 'black',
                    textDecoration: 'none',
                  }}
                >
                  Products
                </Link>
              </li>
              <li>
                <Link
                  href="/card"
                  style={{
                    color: 'black',
                    textDecoration: 'none',
                  }}
                >
                  Product card
                </Link>
              </li>
              <li>
                <Link
                  href="/checkout"
                  style={{
                    color: 'black',
                    textDecoration: 'none',
                  }}
                >
                  Checkout
                </Link>
              </li>
              <li>
                <Link
                  href="/thanks"
                  style={{
                    color: 'black',
                    textDecoration: 'none',
                  }}
                >
                  <FaShoppingCart className={styles.icon} />
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        <footer>
          <div>
            <h5>Contact Us</h5>
            <div>
              {/* <FontAwesomeIcon className={styles.icon} icon={faLocationDot} /> */}
              <p>Lorem ipsum viverra feugiat tesque libero ut</p>
            </div>
            <div>
              {/* <FontAwesomeIcon className={styles.icon} icon={faPhone} /> */}
              <p>+ 48 5854995838</p>
            </div>
            <div>
              {/* <FontAwesomeIcon className={styles.icon} icon={faEnvelope} /> */}
              <p>cofee@gmail.com</p>
            </div>
          </div>

          <div>
            <h5>Newsletter</h5>
            <div>
              {/* <FontAwesomeIcon className={styles.icon} icon={faLocationDot} /> */}
              <p>Get in your inbox the latest News and</p>
              <form>
                <input />
                <button>
                  {/* <FontAwesomeIcon className={styles.icon} icon={faEnvelope} /> */}
                </button>
              </form>
            </div>
            <a href="/#">Giveaways</a>
            <a href="/#">Referral Hub</a>
            <a href="/#">Analytics</a>
            <a href="/#">Integrations</a>
          </div>
          <div>
            <h5>FEATURES</h5>
            <a href="/#">Rewards</a>
            <a href="/#">Giveaways</a>
            <a href="/#">Referral Hub</a>
            <a href="/#">Analytics</a>
            <a href="/#">Integrations</a>
          </div>
        </footer>
      </body>
    </html>
  );
}
